
// Extensión Paste JSON as Code
// https://pokeapi.co/



// Generated by https://quicktype.io

export class Pokemon {
    abilities:                Ability[];
    base_experience:          number;
    forms:                    Species[];
    game_indices:             GameIndex[];
    height:                   number;
    held_items:               HeldItem[];
    id:                       number;
    is_default:               boolean;
    location_area_encounters: string;
    moves:                    Move[];
    name:                     string;
    order:                    number;
    species:                  Species;
    sprites:                  Sprites;
    stats:                    Stat[];
    types:                    Type[];
    weight:                   number;
}

export class Ability {
    ability:   Species;
    is_hidden: boolean;
    slot:      number;
}

export class Species {
    name: string;
    url:  string;
}

export class GameIndex {
    game_index: number;
    version:    Species;
}

export class HeldItem {
    item:            Species;
    version_details: VersionDetail[];
}

export class VersionDetail {
    rarity:  number;
    version: Species;
}

export class Move {
    move:                  Species;
    version_group_details: VersionGroupDetail[];
}

export class VersionGroupDetail {
    level_learned_at:  number;
    move_learn_method: Species;
    version_group:     Species;
}

export class Sprites {
    back_default:       string;
    back_female:        null;
    back_shiny:         string;
    back_shiny_female:  null;
    front_default:      string;
    front_female:       null;
    front_shiny:        string;
    front_shiny_female: null;
}

export class Stat {
    base_stat: number;
    effort:    number;
    stat:      Species;
}

export class Type {
    slot: number;
    type: Species;
}
